// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOPRTIqpqMVuIqzUwcvJku6kmeWNyvR9c',
    appId: '1:435476889292:web:51979ead5311ece3304c69',
    messagingSenderId: '435476889292',
    projectId: 'meals-application-868fe',
    authDomain: 'meals-application-868fe.firebaseapp.com',
    storageBucket: 'meals-application-868fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9cK0malX_zs6c1BTkszcdlh43CHRENXk',
    appId: '1:435476889292:android:6888645b3845d78f304c69',
    messagingSenderId: '435476889292',
    projectId: 'meals-application-868fe',
    storageBucket: 'meals-application-868fe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOPRTIqpqMVuIqzUwcvJku6kmeWNyvR9c',
    appId: '1:435476889292:web:c119296c504c237c304c69',
    messagingSenderId: '435476889292',
    projectId: 'meals-application-868fe',
    authDomain: 'meals-application-868fe.firebaseapp.com',
    storageBucket: 'meals-application-868fe.firebasestorage.app',
  );
}
